## Users [/users]
Users of the navi app

### create [POST]
Creates a new user

+ Request (application/json; charset=utf-8)

        {
          "email": "user1@teste.com",
          "name": "Usuário teste"
        }

+ Response 200

        {
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }

### index [GET]
Gets list of users

+ Request (application/json; charset=utf-8)

+ Response 200

        [{
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }]


## User [/users/{userId}]

+ Parameters
    + userId: `meuid` (required, string) 1 - ID of the user on DB

### show [GET]

+ Response 200

        {
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }

### update [PUT]

+ Request (application/json; charset=utf-8)

        {
          "name": "bloblo"
        }

+ Response 200

        {
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }

### delete [DELETE]

+ Response 200

        {
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }
