## Users [/users]
Users of the navi app

### Create new user [POST]
Creates a new user

+ Request (application/json; charset=utf-8)

        {
          "email": "user1@teste.com",
          "name": "Usuário teste"
        }

+ Response 200

        {
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }

### Index of Users [GET]
Gets list of users

+ Request (application/json; charset=utf-8)

+ Response 200

        [{
          "_id": "meu id",
          "name": "blabla",
          "email": "user1@teste.com",
          "createdAt":  "blabla",
          "updatedAt":  "blabla"
        }]


## User [/users/{userId}]

+ Parameters
    + userId: `1` (required, string) 1 - ID of the user on DB

### Show user [GET]

+ Response 200

